### ISSUE TITLE
Please update .gemspec reset-client to latest version

### ISSUE THREAD

**Issue by virudson** [omise/omise-ruby#21]
there was error on `rest-client 1.8`
I'm on `ruby-2.4.1` so `OpenSSL::SSL::SSLContext::DEFAULT_PARAMS` not include `:ciphers` key

https://github.com/rest-client/rest-client/blob/v1.8.0/lib/restclient/request.rb#L159-L166

**Comment by robinclart** [comment]
Hey @virudson. Sorry, was in holiday and just got back this morning. I will update and publish a new version with the updated gemspec.

**Comment by robinclart** [comment]
@virudson this should be fixed as of 00fad49. Update the gem to 0.5.1.
