### ISSUE TITLE
Could you use JSON.parse instead of JSON.load?

### ISSUE THREAD

**Issue by midnight-wonderer** [omise/omise-ruby#60]
### Expected behavior

JSON.parse usage
(bad template; there is no place to provide a proper explanation. will comment later)

### Actual behavior

JSON.load usage
(bad template; there is no place to provide a proper explanation. will comment later)

### Steps to reproduce the issue

Simply using the library

### Name and version information

SDK: omise (0.11.0)
Package Manager: bundler
Operating System: Linux

**Comment by midnight-wonderer** [comment]
You see the JSON usage here
https://github.com/omise/omise-ruby/blob/a0efda8b226c92943eb4541446e19aeb1c55194a/lib/omise/util.rb#L20

Typically, `JSON.load` and `JSON.parse` are somewhat interchangeable.
But they differ under some circumstances. And that circumstance just happened today.

MultiJSON, used in Rails projects, allows configuring different JSON parsers. I use [Oj](https://github.com/ohler55/oj) in my projects via [Oj.optimize_rails](https://github.com/ohler55/oj/blob/develop/pages/Rails.md).

The issue is, with such configuration, `JSON.load` will raise `Oj::ParseError` while `JSON.parse` will raise `JSON::ParserError`.
And that parse error will occur when there are faults in Omise's responses.
Today, the new backend deployed by Opn is at fault for returning malformed JSON, which made me notice the error.

Could you change `JSON.load` here to `JSON.parse`?

**Comment by aashishgurung** [comment]
@midnight-wonderer Thanks for reaching out. We will look into this and let you know about our findings. We will need more details about the issue. Can you please shed more light on the faults in Omise's responses?

**Comment by midnight-wonderer** [comment]
Disscussed with the support in ticket no. 646321

**Comment by aashishgurung** [comment]
@midnight-wonderer We are closing this issue as our support team confirmed it has already been resolved. Thank you.

**Comment by midnight-wonderer** [comment]
@aashishgurung
That is that, and this is this.

The internal server error isn't there anymore.
But the client software is still broken. I can't rescue the error properly.
Should I send a pull request?

**Comment by aashishgurung** [comment]
@midnight-wonderer Thank you for submitting the PR. We'll review and test the changes, and proceed accordingly.
